# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mlAccelData' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mlAccelData
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  target 'mlAccelDataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mlAccelDataUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
